name: Vehicle Telemetry CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python Dependencies

        run: | 
          pip install -r requirements.txt

      - name: Run Lint Check 
        run: |
          echo "flake8 backend - not using now this feature to save time"

      - name: Build Containers
        run: docker compose build

      - name: Start Containers
        run: docker compose up -d

      - name: Wait for Backend
        run: ./scripts/wait_for_backend.sh

      - name: Check Backend Health
        run: curl http://localhost:5000/health